AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bugs-api-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: python3.9
    Architectures:
      - x86_64
    Environment:
      Variables:
        BUGS_TABLE: !Ref BugsTable

Resources:
  BugsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
        
  BugsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}

  CreateBugFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bugs_api/
      Handler: create.lambda_handler
      Events:
        CreateBug:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bugs
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BugsTable
    
  ReadBugFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bugs_api/
      Handler: read.lambda_handler
      Events:
        ReadBug:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /bugs/{id}
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref BugsTable
  
  BatchProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bugs_api/
      Handler: batch.lambda_handler
      Events:
        BugDataFileEvent:
          Type: S3
          Properties:
            Bucket: !Ref BugsS3Bucket
            Events: s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}
      

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateBugApi:
    Description: "API Gateway endpoint URL for Prod stage for create bug function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/bugs/"
  CreateBugFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt CreateBugFunction.Arn
  CreateBugFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CreateBugFunctionRole.Arn
